### ISSUE TITLE
not work on Sony xzp 8.0

### ISSUE THREAD

**Issue by klcb2010** [itandy/Sony-Status-Activity-Fix#1]
test on 47.1.A.12.75

**Comment by itandy** [comment]
Can you send me the Xposed log?

**Comment by klcb2010** [comment]
@itandy  https://ghostbin.com/paste/68n39

**Comment by itandy** [comment]
Sorry I cannot see anything wrong in your log. Can you try disabling all other modules? Maybe there's a conflict.

**Comment by klcb2010** [comment]
@itandy  https://ghostbin.com/paste/gwmjm

**Comment by itandy** [comment]
Are you using Sony stock firmware? I see MI 6 (Xiaomi) from your Xposed log.

**Comment by klcb2010** [comment]
@ itandy sure, Sony stock firmware!  MI 6 is a magisk module

**Comment by itandy** [comment]
Unfortunately there's nothing in the Xposed log. If you can get me a deodexed SystemUI.apk, then I can take a look at the code for your ROM.

**Comment by klcb2010** [comment]
SystemUI.zip
https://pan.baidu.com/s/1HkbZK2D3kUmG3zL8fLuTMQ here

**Comment by itandy** [comment]
Sorry that your APK is odexed. I need it to be deodexed so as to decompile it into reading Java codes
